networks:
  inception:

volumes:
  db_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb:42
    container_name: "mariadb"
    env_file: .env
    networks: [inception]
    volumes: [db_data:/var/lib/mysql/:rw]
    restart: on-failure

  wordpress:
    build: requirements/wordpress/
    image: wordpress:42
    container_name: "wordpress"
    env_file: .env
    networks: [inception]
    volumes: [wp_data:/var/www/html/:rw]
    restart: on-failure

  nginx:
    build: requirements/nginx/
    image: nginx:42
    container_name: "nginx"
    env_file: .env
    networks: [inception]
    volumes: [wp_data:/var/www/html/:r]
    restart: on-failure
    ports: ["443:443"]
