services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb:42
    container_name: "mariadb"
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - type: bind
        source: /home/${USER}/data/mariadb
        target: /var/lib/mysql/
    restart: on-failure
