networks:
  inception:

volumes:
  db_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb:42
    container_name: "mariadb"
    env_file: .env
    networks: [inception]
    volumes: [db_data:/var/lib/mysql/:rw]
    restart: on-failure
    healthcheck:
      test: mariadb-admin ping -hmariadb -u$MYSQL_USER -p$MYSQL_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  wordpress:
    build: requirements/wordpress/
    image: wordpress:42
    container_name: "wordpress"
    env_file: .env
    networks: [inception]
    volumes: [wp_data:/var/www/html/:rw]
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: nc -z wordpress 9000
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    build: requirements/nginx/
    image: nginx:42
    container_name: "nginx"
    env_file: .env
    networks: [inception]
    volumes: [wp_data:/var/www/html/:r]
    restart: on-failure
    ports: ["443:443"]
    depends_on:
      wordpress:
        condition: service_healthy
